title: Thunderspy Gaming
timezone: UTC
description: 
url: "."
theme: 

collections:    
  highlights:
    title: Highlights
    output: false

  patchnotes:
    title: Patch Notes
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      type: "patchnotes"
    values:
      layout: "inner"