title: Thunderspy Gaming
email: your-email@example.com
timezone: UTC
description: 
url: "."
theme: 

collections:
  media:
    title: Media
    output: false
    
  highlights:
    title: Highlights
    output: false

default:
- scope:
    path: ''
    type: Media
  values:
    image: 
 
- scope
    path: ''
    type: 'highlights'
  values:
    image: