title: Thunderspy Gaming
timezone: UTC
description: 
url: "https://tspydev.eccentric.monster/"
theme: 

collections:    
  highlights:
    title: Highlights
    output: false

  patchnotes:
    title: Patch Notes
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: "/patchnotes"
    values:
      layout: "inner"
  -
    scope:
      type: "patchnotes"
    values:
      layout: "patchnote"