title: Thunderspy Gaming
timezone: UTC
url: "https://tspydev.eccentric.monster/"
theme: 
plugins:
  - jekyll-feed

collections:    
  highlights:
    title: Highlights
    output: false

  galleryvideos:
    title: Gallery Videos
    output: false

  galleryimages:
    title: Gallery Images
    output: false

  patchnotes:
    title: Patch Notes
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: "/patchnotes"
    values:
      layout: "inner"
  -
    scope:
      type: "patchnotes"
    values:
      layout: "patchnote"

feed:
  collections:
    patchnotes:
      path: "/patchnotes.xml"