title: Thunderspy Gaming
email: your-email@example.com
timezone: UTC
description: 
url: "."
theme: 

collections:    
  highlights:
    title: Highlights
    output: false

default:
- scope
    path: ''
    type: highlights
  values:
    image: