title: Thunderspy Gaming
timezone: UTC
description: 
#url: "http://localhost:4000/"
url: "https://crekulon.github.io/tspy/"
theme: 

collections:    
  highlights:
    title: Highlights
    output: false

  patchnotes:
    title: Patch Notes
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      type: "patchnotes"
    values:
      layout: "inner"