title: Thunderspy Gaming
email: your-email@example.com
timezone: UTC
description: 
url: "."

collections:
  media:
    title: Media
    output: false
  hooks:
    title: Hooks
    output: false

default:
- scope:
    path: ''
    type: Media
  values:
    image: 