description: "Featuring massive character customization improvements, pet customization, new powersets and more, Thunderspy is the most advanced City of Heroes private server."
image: "https://eccentric.monster/tspy/img/thundersplash.png"
favicon: "https://crekulon.github.io/tspy/img/coxgfv.png"