description: " Con mejoras masivas de personalización de personajes, nuevos
  poderes y mucho más, Thunderspy es el servidor privado más avanzado de City of
  Heroes."
image: https://eccentric.monster/tspy/img/thundersplash.png
favicon: https://crekulon.github.io/tspy/img/coxgfv.png
