backend:
  name: github
  repo: crekulon/tspy
  branch: main
  site_domain: nervous-einstein-3d330a.netlify.com

media_folder: "img/uploads"
site_url: https://tspydev.eccentric.monster/
show_preview_links: false

collections:
  - name: "patchnotes"
    label: "Patch Notes"
    folder: "_patchnotes"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "homepage"
    label: "Homepage & Metadata"
    files:
      - label: "Metadata"
        name: "meta"
        file: "_data/meta.yml"
        fields: 
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Social Sharing Image", name: "image", widget: "image"}
          - {label: "Site Icon", name: "favicon", widget: "image"}

      - label: "Mottos"
        name: "mottos"
        file: "_data/mottos.yml"
        fields: 
          - {label: "Larger Motto", name: "largermotto", widget: "markdown"}
          - {label: "Smaller Motto", name: "smallermotto", widget: "markdown"}

      - label: "How To Play"
        name: "howtoplay"
        file: "_data/howtoplay.yml"
        fields: 
          - {label: "Body", name: "body", widget: "markdown"}
          
      - label: "About Us"
        name: "aboutus"
        file: "_data/aboutus.yml"
        fields: 
          - {label: "Body", name: "main", widget: "markdown"}
          - {label: "Support Us", name: "support", widget: "markdown"}
          
      - label: "Policies"
        name: "policies"
        file: "_data/policies.yml"
        fields: 
          - {label: "Code of Conduct", name: "coc", widget: "markdown"}
          - {label: "Terms of Service", name: "tos", widget: "markdown"}

  - name: "highlights"
    label: "Homepage Highlights"
    folder: "_highlights"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Order", name: "order", widget: "number", default: 1, value_type: "int"}