backend:
  name: github
  repo: crekulon/tspy
  branch: main
  site_domain: nervous-einstein-3d330a.netlify.com

media_folder: "img/uploads"
site_url: https://tspydev.eccentric.monster/
show_preview_links: false

collections:
  - name: "patchnotes"
    label: "Patch Notes"
    folder: "_patchnotes"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}"
    fields: 
      - {label: "Date", name: "date", widget: "datetime", hint: "Patch notes are sorted by their date"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image", default: "/img/qachan.png"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "guides"
    label: "Guides"
    folder: "_guides"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}"
    fields: 
      - {label: "Category", name: "category", widget: "string", hint: "Guides need a category to be 'under'. You can leave this as 'General', name one already being used, or even name a new one completely.", default: "General"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "homepage"
    label: "Homepage & Metadata"
    files:
      - label: "Metadata"
        name: "meta"
        file: "_data/meta.yml"
        fields: 
          - {label: "Description", name: "description", widget: "string", hint: "This is what links on discord/twitter/etc will show as preview text"}
          - {label: "Social Sharing Image", name: "image", widget: "image", hint: "Ditto but this is the image that's shown with it"}
          - {label: "Site Icon", name: "favicon", widget: "image", hint: "The little tab icon"}

      - label: "Mottos"
        name: "mottos"
        file: "_data/mottos.yml"
        fields: 
          - {label: "Larger Motto", name: "largermotto", widget: "string"}
          - {label: "Smaller Motto", name: "smallermotto", widget: "string"}

      - label: "How To Play"
        name: "howtoplay"
        file: "_data/howtoplay.yml"
        fields: 
          - {label: "Body", name: "body", widget: "markdown"}
          
      - label: "About Us"
        name: "aboutus"
        file: "_data/aboutus.yml"
        fields: 
          - {label: "Body", name: "main", widget: "markdown"}
          - {label: "Support Us", name: "support", widget: "markdown", hint: "This is shown beneath the regular 'about us' stuff in a highlighted box"}
          
      - label: "Policies"
        name: "policies"
        file: "_data/policies.yml"
        fields: 
          - {label: "Code of Conduct", name: "coc", widget: "markdown"}
          - {label: "Terms of Service", name: "tos", widget: "markdown"}

  - name: "highlights"
    label: "Homepage Highlights"
    folder: "_highlights"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Order", name: "order", widget: "number", default: 1, value_type: "int", hint: "You can use this number to change the order in which highlights appear on the homepage. Lower is closer to the top. You don't have to change this if you don't care about the order."}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "galleryvideos"
    label: "Gallery Videos"
    folder: "_galleryvideos"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string", hint: "This isn't used on the front-end, it's just for internal reference."}
      - {label: "Video ID", name: "body", widget: "string", hint: "Get the youtube ID from the URL and put it here. For example, that'd be ''Aqb-qH7mwrE'' from ''https://www.youtube.com/watch?v=Aqb-qH7mwrE''. It's everything after the ?v=!"}
      - {label: "Order", name: "order", widget: "number", default: 1, value_type: "int", hint: "You can use this number to change the order in which videos appear in the gallery. Lower is closer to the top. The 'first' will be a big, highlighted video! You don't have to change this if you don't care about the order."}
      
  - name: "galleryimages"
    label: "Gallery Images"
    folder: "_galleryimages"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string", hint: "This isn't used on the front-end, it's just for internal reference."}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Order", name: "order", widget: "number", default: 1, value_type: "int", hint: "You can use this number to change the order in which videos appear in the gallery. Lower is closer to the top/left. You don't have to change this if you don't care about the order."}